// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxndgbdmgvfheucntkbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bmRnYmRtZ3ZmaGV1Y250a2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTcyNjIsImV4cCI6MjA3NDM3MzI2Mn0.SIWSN6LLp9WkW1yVJKAjJfHVzyAG2NtIq-WSbmOdcd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});